engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - "src/**"
  - "tasks/**"
exclude_paths:
- "src/**/__tests__"
