language: node_js
node_js:
  - "7"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
after_script:
  - "npm install -g coveralls"
  - "cat coverage/lcov.dat | coveralls"
