# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Update NPM Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The targeted published version'
        required: true
      tag:
        description: 'The tag to publish to: latest | next'
        required: true

jobs:
  update-npm-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check Tag Name
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm dist-tag add @adobe/reactor-turbine@${{version}} ${{tag}}
        env:
          NPM_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
        with:
          tag: ${{ github.event.inputs.tag }}
          version: ${{ github.event.inputs.version }}
